# Generated by Django 2.0.5 on 2018-05-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180530_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='objective',
            new_name='task',
        ),
    ]
